### ISSUE TITLE
Hide download button

### ISSUE THREAD

**Issue by RaitaroH** [style-it-themes/discord-inspired-bits-dark#4]
If one is using the browser version, one has no need to see the download button.

```
.downloadAppButton-3EFlA6 {
    display: none !important;
}
```

**Comment by the-j0k3r** [comment]
The idea I imagine Discord has is to give people options, so I think this one should to be optional also.

If you wanna push a PR for that, so much the better :smiley:

**Comment by RaitaroH** [comment]
I will do that tomorrow.
