### ISSUE TITLE
Weird white background when fast tiling

### ISSUE THREAD

**Issue by RaitaroH** [style-it-themes/discord-inspired-bits-dark#6]
* **Browser**: Firefox 61
* **Operating System**: KDE Neon
* **Screenshot/gif**: 
![screenshot_20180827_090751](https://user-images.githubusercontent.com/19552720/44643391-0a439a00-a9d9-11e8-8bf7-c1920d7f960d.png)

* **HTML of the section where the issue occurs**:
I can't find it XD. I looked for quite a while but I am starting to think it is firefox only. I want to know if it is.

**Comment by RaitaroH** [comment]
Yeah, I am 99% sure is the firefox window. I only wonder how that could be fixed.

**Comment by the-j0k3r** [comment]
Nor me.

Can you duplicate this without theme enabled?

**Comment by RaitaroH** [comment]
Yeah same thingy. I think is the firefox window itself. If you do find something... tell me about it. But till that...
